apiVersion: coralogix.com/v1alpha1
kind: RuleGroup
metadata:
  labels:
    app.kubernetes.io/name: rulegroup
    app.kubernetes.io/instance: rulegroup-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: json-stringify-rule
spec:
  name: json-stringify-rule
  description: rule-group from k8s operator
  subgroups:
    - rules:
        - name: Json stringify
          jsonStringify:
            sourceField: text
            destinationField: text
            keepSourceField: false
