apiVersion: coralogix.coralogix/v1alpha1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: flow-alert-example
spec:
  name: flow alert example
  description: alert from k8s operator
  severity: Critical
  notificationGroups:
    - groupByFields: [ "coralogix.metadata.sdkId" ]
      notifications:
        - notifyOn: TriggeredOnly
          integrationID: 2235
          retriggeringPeriodMinutes: 1
        - notifyOn: TriggeredAndResolved
          emailRecipients: [ "example@coralogix.com" ]
          retriggeringPeriodMinutes: 1440
  scheduling:
    daysEnabled: ["Wednesday", "Thursday"]
    timeZone: UTC+02
    startTime: 08:30
    endTime: 20:30
  alertType:
    flow:
      stages:
        - groups:
            - innerFlowAlerts:
                alerts:
                  - not: true
                    userAlertId: cb998390-f28b-40e9-b8ed-97eaa6aa240b
                  - not: false
                    userAlertId: cb998390-f28b-40e9-b8ed-97eaa6aa240b
                operator: And
              nextOperator: And
          timeWindow:
            minutes: 20
        - groups:
            - innerFlowAlerts:
                alerts:
                  - not: true
                    userAlertId: cb998390-f28b-40e9-b8ed-97eaa6aa240b
                operator: And
              nextOperator: Or
          timeWindow:
            minutes: 20
