apiVersion: coralogix.com/v1alpha1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: standard-alert-example
spec:
  name: standard alert example
  description: alert from k8s operator
  severity: Info
  labels:
    alert_type: security
    security_severity: high
  notificationGroups:
    - notifications:
        - notifyOn: TriggeredOnly
          integrationName: slack-webhook
          retriggeringPeriodMinutes: 1
        - notifyOn: TriggeredAndResolved
          emailRecipients: [ "example@coralogix.com" ]
          retriggeringPeriodMinutes: 1440
    - groupByFields: [ "coralogix.metadata.sdkId" ]
      notifications:
        - notifyOn: TriggeredOnly
          integrationName: WebhookAlerts
          retriggeringPeriodMinutes: 1
        - notifyOn: TriggeredAndResolved
          emailRecipients: [ "example2@coralogix.com" ]
          retriggeringPeriodMinutes: 1440
  scheduling:
    daysEnabled: [ "Wednesday", "Thursday" ]
    timeZone: UTC+02
    startTime: 08:00
    endTime: 20:00
  alertType:
    standard:
      filters:
        searchQuery: remote_addr_enriched:/.*/
        applications: [ "filter:contains:nginx" ]
        subsystems: [ "filter:startsWith:subsystem-name" ]
        severities: [ "Warning", "Info" ]
      conditions:
        alertWhen: More
        threshold: 5
        timeWindow: FiveMinutes
        groupBy: [ "coralogix.metadata.sdkId" ]